right_format = """$cmd_duration$time$battery"""

[time]
disabled = false
format = "[$time]($style)"
style = "bold cyan"

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[cmd_duration]
format = "[$duration]($style)/"

[package]
disabled = true

[memory_usage]
disabled = false
symbol = " "

[aws]
symbol = "  "
format = 'as [$symbol($profile )(\[$duration\])]($style)'

[conda]
symbol = " "
disabled = true

[dart]
symbol = " "
disabled = true

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "
disabled = true

[elm]
symbol = " "
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "
disabled = true

[hg_branch]
symbol = " "

[java]
symbol = " "
disabled = true

[julia]
symbol = " "
disabled = true

[nim]
symbol = " "
disabled = true

[nix_shell]
symbol = " "

[perl]
symbol = " "
disabled = true

[php]
symbol = " "
disabled = true

[python]
symbol = " "
disabled = true

[ruby]
symbol = " "
disabled = true

[rust]
symbol = " "
disabled = true

[scala]
symbol = " "
disabled = true

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
disabled = true
